### ISSUE TITLE
Sonoma compatibility

### ISSUE THREAD

**Issue by silentdragoon** [wwwjfy/GMailinator#12]
This doesn't seem to work in Sonoma due to the changes to the Mail app here. For example, extensions appear to have been replaced with plugins and the terminal command given in the readme doesn't seem to work. Still very early of course, given Sonoma is still in beta, but thought I'd see if there were any plans to work on this - I'm happy to donate a coffee or two for the cause!

**Comment by wwwjfy** [comment]
I have no plan to try Sonoma when it's still beta, though I probably will upgrade in the first few days when it's released.

Pull request is more than welcomed to support it.

**Comment by wwwjfy** [comment]
Sadly, Sonoma no longer supports legacy plug-in.
Its new supposed-to-be-replacement MailKit can't do as much as before, in this case shortcuts.

I'm afraid I need to find other mail clients :(
