### ISSUE TITLE
Support for Big Sur 11.6 and Mail 14.0

### ISSUE THREAD

**Issue by mjabdulm** [wwwjfy/GMailinator#3]
Hi,

Could you please enable support for Big Sur 11.6 and Mail 14.0?

Thanks,
Abdul

**Comment by wwwjfy** [comment]
updated.

btw, this can be easily done by building locally.

**Comment by mjabdulm** [comment]
Hi Tony,

Thanks a lot. Somehow I wasn't successful. in building it.
