### ISSUE TITLE
question regarding mail.app version 15.0

### ISSUE THREAD

**Issue by ivotron** [wwwjfy/GMailinator#4]
I install this by building it on 12.2 with mail.app 15.0. The bundle is built with the proper value for `Supported12.2PluginCompatibilityUUIDs` (specifically `6FF8B077-81FA-45A4-BD57-17CDE79F13A5`). Would you happen to know why, after enabling the plugin and restarting the Mail.app, the `Contact the makers of these plug-ins for versions that are compatible with Mail 15.0.` message is still showing up?

Any help would be much appreciated! 🙏

**Comment by wwwjfy** [comment]
can try these steps: https://github.com/wwwjfy/GMailinator#allow-usage-in-big-sur

**Comment by ivotron** [comment]
> can try these steps: https://github.com/wwwjfy/GMailinator#allow-usage-in-big-sur

thank you for the prompt reply! I should have mentioned that I follow those instructions: enabled `Automatically manage signing` in Xcode as well as `Allow in system policy`. But no luck... 😢

**Comment by ivotron** [comment]
found the issue! I didn't realize that XCode had selected to target a Rosetta build (I'm on an M1 and it's the first time I'm building for an M1). Thanks a lot for your time!

**Comment by wwwjfy** [comment]
Thanks for the info. When I get touch with M1, will try to see if we can build it without updating Xcode project. Feel free to create pull request if you know how to do it already. :D

**Comment by ivotron** [comment]
I actually don't see any difference in the `project.pbxproj` file (other than the auto signing and team id entries). I think this option is a global one and it's outside the project

**Comment by wwwjfy** [comment]
Thanks. interesting 🤔
