### ISSUE TITLE
Probably User Error, Don't see "Manage Plug-ins" in Mail.app

### ISSUE THREAD

**Issue by loudestnoise** [wwwjfy/GMailinator#5]
Steps I've done

- Cloned project on my Mac
- Codesigned and built in Xcode
- Copied `Gmailinator.bundle` from `/tmp/Gmailinator` to `~/Library/Mail/Bundles`
- Opened Mail.app and went to Preferences and clicked on General.
- Here's where I'm stuck. I don't see where I enable the plugin.

![image](https://user-images.githubusercontent.com/194853/179804484-1d620eba-79c9-40f4-b9d5-884e1f3819f1.png)

I am using the latest commits, which I saw said it should work with macOS Monterrey 12.4, which I'm on.

**Comment by wwwjfy** [comment]
can try to run `defaults write com.apple.mail EnableBundles -bool YES`

**Comment by loudestnoise** [comment]
I did try that, and found this page and tried the other two they suggested for their plug-in.

https://help.mailbutler.io/help/manage-plug-ins-button-is-gone-from-apple-mail

`defaults write com.apple.mail EnableBundles -bool true`
`defaults write com.apple.mail BundleCompatibilityVersion 4`

Also tried rebooting the Mac for good measure.

**Comment by loudestnoise** [comment]
Ah, so it was apparently because Mail.app didn't see Gmailinator as a bundle. I installed this Mail Butler app and their installer I guess caused the bundle to be "installed" in `~/Library/Mail/Bundles`, and now both it and Gmailinator show up 🤙 

![image](https://user-images.githubusercontent.com/194853/180022421-24ceb16f-4cb1-402b-8956-f6e7c0f7c347.png)

**Comment by loudestnoise** [comment]
Well shoot, spoke too soon. I get this after enabling it and restarting Mail.app

![2022-07-20_10-30-22](https://user-images.githubusercontent.com/194853/180022906-0e6e2bcc-8a65-41a5-a064-99b1167d5699.png)

**Comment by wwwjfy** [comment]
Two possible reasons I ever met:
1. not latest one. need to update Info.plist for each new macOS release
2. didn't run spctl to pass system security check. check readme for the command

**Comment by loudestnoise** [comment]
Hmm, I cloned the repo so I don't think it's 1, and I did the spctl thing as well. Here's a quick video of me starting from scratch and now I get "developer cannot be verified" which makes me thinks it's related to the code signing or spctl, but ¯\_(ツ)_/¯

[https://drive.google.com/file/d/1BAcbr19_eXgRLnfRvWWfeLUdkLw15bBI/view?usp=sharing](https://drive.google.com/file/d/1BAcbr19_eXgRLnfRvWWfeLUdkLw15bBI/view?usp=sharing)

**Comment by wwwjfy** [comment]
I haven't used xcode managed signing for this before. One way to verify is to run `codesign -d -vvv ~/Library/Mail/Bundles/GMailinator.mailbundle/`

Also I suspect xcode only signs the output when during the distribution process, but not the build process.
I think you can try to use command line to codesign the bundle. The identity can be found in keychain, in the format of `Developer ID Application: Your Name`

**Comment by loudestnoise** [comment]
Ah, ok, yup it's not doing the code signing

```
$ codesign -d -vvv ~/Library/Mail/Bundles/GMailinator.mailbundle/
/Users/loudestnoise/Library/Mail/Bundles/GMailinator.mailbundle/: bundle format unrecognized, invalid, or unsuitable
```

Maybe I should try and use the releases method because I did something wrong with Xcode? Problem is when I download from Releases page I don't see 1.0.12, so I clicked on Tags and see it there. I download the .zip and I see this when I open the folder up in Finder. I don't see the .bundle folder so I wasn't sure what I do next. As it may be clear, I'm not a software developer, but I do use Xcode to "build" an app for my iPhone regularly, so I can follow steps pretty well 😄 .

![image](https://user-images.githubusercontent.com/194853/180262208-0a893e4a-8133-4219-b475-80fd30ed1e6e.png)

![image](https://user-images.githubusercontent.com/194853/180262254-1962905f-5f41-4bdc-bf86-bd9336e039f1.png)

**Comment by wwwjfy** [comment]
> bundle format unrecognized, invalid, or unsuitable

This is not right. If it's not codesigned, it should be `/Users/tony/Library/Mail/Bundles/GMailinator.mailbundle: code object is not signed at all`

It's totally fine to build your own. I forgot to upload new releases since some versions ago, downloading it from the tag page is only the source code, not the compiled files.

I'd suggest to still build your own, and use `codesign -s "<Replace with the identity>" -v -f ~/Library/Mail/Bundles/GMailinator.mailbundle`, instead of using Xcode.

The files in /tmp is not a "normal" "app", installing the app to your phone is kind of "distribution" where Xcode will codesign it, but this one is not.
I should probably remove that part in the README, to avoid confusing others.

**Comment by loudestnoise** [comment]
Gah, I'm getting closer, but I'm missing something. I was able to codesign it using your instructions, but now Mail says this -

![image](https://user-images.githubusercontent.com/194853/180271082-d654f340-4b22-405a-b856-cc06dcbf103d.png)

When I check for codesigning it seems like it worked.

```
loudestnoise:GMailinator/ $ codesign -d -vvv ~/Library/Mail/Bundles/GMailinator.mailbundle/                                SGV: 175 @ 11:54
Executable=/Users/loudestnoise/Library/Mail/Bundles/GMailinator.mailbundle/Contents/MacOS/GMailinator
Identifier=com.nompute.gmailinator.GMailinator
Format=bundle with Mach-O thin (arm64)
CodeDirectory v=20400 size=903 flags=0x0(none) hashes=21+3 location=embedded
Hash type=sha256 size=32
CandidateCDHash sha256=ecad4d6e33355126ddddcf2dd58d9b3cb604557c
CandidateCDHashFull sha256=ecad4d6e33355126ddddcf2dd58d9b3cb604557c1e42386b7000061c82beaf5f
Hash choices=sha256
CMSDigest=ecad4d6e33355126ddddcf2dd58d9b3cb604557c1e42386b7000061c82beaf5f
CMSDigestType=2
CDHash=ecad4d6e33355126ddddcf2dd58d9b3cb604557c
Signature size=4783
Authority=Apple Development: David Cintron (ABCDEFGHIJ)
Authority=Apple Worldwide Developer Relations Certification Authority
Authority=Apple Root CA
Signed Time=Jul 20, 2022 at 11:03:37
Info.plist entries=39
TeamIdentifier=[redacted]
Sealed Resources version=2 rules=13 files=2
Internal requirements count=1 size=200
```

I checked and in Security & Privacy I do have the `Allow apps downloaded from: App Store and identified developers`, thinking it might have something to do with that.

**Comment by wwwjfy** [comment]
This looks like what spctl can fix. I'm not sure how it works, but seems I can not remove it from the trusted list to reproduce it.

**Comment by loudestnoise** [comment]
Yeah, weird. I did get it working, but only on my Intel MacBook Pro. Not sure if my M1 MacBook Air was causing the issue. On the MacBook Pro though I had to edit the Info.plist with the `Supported12.4PluginCompatibilityUUIDs` despite it being the same value that you had already updated. Saved the file, built again in Xcode and then 🧙‍♂️ it just worked 🌟 .

**Comment by wwwjfy** [comment]
I tried on M1 machine. If you copied the compiled file from Intel machine, it'll fail because arch mismatch.

You can try latest commit or download the release, which is universal build. Then spctl should make it work.

**Comment by loudestnoise** [comment]
Got it working now on the M1 Mac. For some reason it kept complaining about not being able to scan for malicious code, and it turned out it had to do with Terminal not being given Full Disk Access. I changed that in Security & Privacy, and then re-ran

`sudo codesign -f -s - ~/Library/Mail/Bundles/Gmailinator.mailbundle`
and
`spctl --add ~/Library/Mail/Bundles/GMailinator.mailbundle`

and then finally I was able to get it going.

**Comment by fcwoknhenuxdfiyv** [comment]
> > bundle format unrecognized, invalid, or unsuitable
> 
> This is not right. If it's not codesigned, it should be `/Users/tony/Library/Mail/Bundles/GMailinator.mailbundle: code object is not signed at all`
> 

I ran into this as well. It seems that if your terminal app doesn't have full disk access, it can't see anything below the Mail directory, so "bundle format unrecognized, invalid, or unsuitable" effectively means it can't read the file.

So, in summary, just allow full disk access to your terminal app before starting the steps in the readme.

**Comment by tarngerine** [comment]
for others:

I had a brand new MBP with Ventura, had to enable Full Disk Access in System Preferences for Terminal, then run `install.sh` and 

```
sudo defaults write “/Library/Preferences/com.apple.mail” EnableBundles 1
sudo defaults write com.apple.mail EnableBundles -bool true
sudo defaults write com.apple.mail BundleCompatibilityVersion 4
```

and restarting Mail app, then Manage Plugins shows up!
