### ISSUE TITLE
New release for Ventura?

### ISSUE THREAD

**Issue by sdgandhi** [wwwjfy/GMailinator#6]
Would be nice to have a release for the new updates for Ventura!

**Comment by wwwjfy** [comment]
I've been pushing changes, and actually even that is not needed, but only to build it once in xcode.
Because codesign and spctl are needed anyway, I think to build is the easier one to do.

**Comment by mpr1255** [comment]
How to build? Ventura update would def be noice.

**Comment by wwwjfy** [comment]
Take a look at readme how to build. You'll need to do code sign and spctl anyway.
