### ISSUE TITLE
Plugin incompatible with Apple Mail 16.0

### ISSUE THREAD

**Issue by erikw** [wwwjfy/GMailinator#8]
I just upgraded to macOS 13.4 which comes with Apple Mail 16.0 and this plugin was automatically disabled on start up as of incompatibility :(.

<img width="315" alt="Screenshot 2023-05-31 at 12 12 37" src="https://github.com/wwwjfy/GMailinator/assets/175286/0721499f-9f6e-4a83-8364-9e8130aa9d82">
<img width="322" alt="Screenshot 2023-05-31 at 12 13 06" src="https://github.com/wwwjfy/GMailinator/assets/175286/2c26a452-28ac-4dbb-91da-ed074e22ab6b">

**Comment by wwwjfy** [comment]
Yes, it happens in every system upgrade, because compatibility UUID is different in new Mail.

Need to rebuild and do all the code signing and spctl again.

**Comment by erikw** [comment]
I see. Thank you for quick support!

I pulled the latest changes and tried to build the project:

```console
$ xcodebuild
[...]
** BUILD FAILED **


The following build commands failed:
        CompileC /Users/erikw/src/github.com/wwwjfy/GMailinator/build/GMailinator.build/Release/GMailinator.build/Objects-normal/x86_64/GMailinator.o /Users/erikw/src/github.com/wwwjfy/GMailinator/GMailinator/GMailinator.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'GMailinator' from project 'GMailinator')
        CompileC /Users/erikw/src/github.com/wwwjfy/GMailinator/build/GMailinator.build/Release/GMailinator.build/Objects-normal/arm64/GMailinator.o /Users/erikw/src/github.com/wwwjfy/GMailinator/GMailinator/GMailinator.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'GMailinator' from project 'GMailinator')
(2 failures)
```

Before it worked to just run `xcodebuild`.

I'm on an M1 machine.

**Edit.**
Ah now I remember, before I compiled a fork of this fork namely https://github.com/jasoncodes/GMailinator/commits/master.

These 2 commits are needed for `xcodebuild` to work in this fork:
* https://github.com/jasoncodes/GMailinator/commit/6d9fc0c1a7e666d29d0f04adf414c10bd70344ef
* https://github.com/jasoncodes/GMailinator/commit/b81c35f23dbee261cde6483145fea1c0d5f0efe4

Any chance these 2 could be applied to this fork as well, so that it compiles? :)

**Comment by wwwjfy** [comment]
I'm using Intel with no such problem.

Sure happy to apply them if there is a PR

**Comment by jasoncodes** [comment]
I’ve opened PR #9 to address the build warnings and errors.

FYI I’m on Intel and also get the build errors. It used to build fine some time ago without this patch so I’m guessing an Xcode update “broke” it.

**Comment by wwwjfy** [comment]
Thanks, will check later.

Interestingly, I'm using latesting xcode (14.3) and don't meet such errors. 🤔

**Comment by wwwjfy** [comment]
I got the reason of `DEBUG` because it's a macro defined in Debug configuration only, while xcodebuild by default uses Release config.

`xcodebuild -configuration Debug` can work. Anyway, it's good to use #ifdef as in your PR.
